services:
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "4000:3100"
    command: -config.file=/loki/local-config.yml
    volumes:
      # - /mnt/user/homeshare_private/appdata/loki:/loki
      - /srv/loki:/loki

    healthcheck:
      test:
        ["CMD-SHELL", "wget -q --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    ports:
      - "4001:3000"
    volumes:
      # - /mnt/user/homeshare_private/appdata/grafana:/var/lib/grafana
      - /srv/grafana:/var/lib/grafana
      # - /mnt/user/homeshare_private/appdata/grafana/provisioning:/etc/grafana/provisioning
      - /srv/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --spider http://localhost:3000/api/health || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    depends_on:
      loki:
        condition: service_healthy
